### ISSUE TITLE
Viewing leads team causes unexpected crash 

### ISSUE THREAD

**Issue by henry-li-06** [cornell-dti/idol#195]
Viewing the `leads` team on the edit teams page (`/admin/teams/edit`) causes an unexpected crash 
![image](https://user-images.githubusercontent.com/65922473/139096415-6bc3d1a7-8f58-4be2-a8ca-2b83193c50ad.png)

**Comment by SamChou19815** [comment]
<img width="1792" alt="Screen Shot 2021-10-31 at 10 48 34" src="https://user-images.githubusercontent.com/4290500/139589172-5aa57276-00bb-4c96-bc1c-e6e6655b031c.png">

It's not reproducible for me...

**Comment by henry-li-06** [comment]
@SamChou19815 oh this got fixed I just forgot to close the issue
