### ISSUE TITLE
"Other subteams" != "former members" (affects all business team members)

### ISSUE THREAD

**Issue by ptwu** [cornell-dti/idol#84]
On the website's Projects page, business team members are listed as "Former Members"

[Example](https://github.com/cornell-dti/nova.cornelldti.org/blob/master/packages/website/data/members/js2968.json). The `otherSubteams` field is a bit of a misnomer, since it manifests on the website as former member status, despite them still working on that team. The `subteam` field only takes a single string.

**Comment by SamChou19815** [comment]
Transferred the issue to IDOL repo since new development on website is happening here.
